### ISSUE TITLE
Does the script need to insert into ApiScopes?

### ISSUE THREAD

**Issue by VictorioBerra** [RockSolidKnowledge/IdentityServer4.Migration.Scripts#3]
Im having issues migrating my test seed data. Clients no longer have access to their scopes. It was my understanding that you only need to migrate over ApiResources and ApiResourceScope, nothing in ApiScopes are required. However, I am seeing that this is not the case.

Am I missing something in my code? Or in order to do this:

```csharp
            var tokenResponse = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
            {
                Address = Path.Join(client.BaseAddress.AbsoluteUri, "connect/token"),
                ClientId = "client",
                ClientSecret = "secret",
                Scope = "resource1.scope1"
            });
```

That means `"resource1.scope1"` MUST exist in ApiScopes?

**Comment by VictorioBerra** [comment]
Actually, I see ApiScopes is edited in-place and therefore does not need to be populated. But I also see it appears to be the case that ApiScopes must be duplicated across ApiResourceScopes. I am sure there is a good reason for this, but I do not fully understand it yet.

**Comment by swetha-adb** [comment]
Hi VictorioBerra . I have similar problem. In Samples, only api resouces were added in mongo db.  api scopes are not added.
If i send "api1" scope from client. it is showing as "Invalid scope"
Please help
