### ISSUE TITLE
upgrading Identity Server from 2.5.3 -> 4.1.1.

### ISSUE THREAD

**Issue by nadeem-nasir** [RockSolidKnowledge/IdentityServer4.Migration.Scripts#4]
Hi, I have identity server  2.5.3 and now want to upgrate to  4.1.1. Can you use these script againt identity server database 2.5.3?

**Comment by scottbrady91** [comment]
Yes, these should work. I don't believe there were any database changes in v3, so it should be a straight forward database migration.
