### ISSUE TITLE
Fix ApiScopes -> ApiResourceScopes for MySQL

### ISSUE THREAD

**Issue by djek-sweng** [RockSolidKnowledge/IdentityServer4.Migration.Scripts#5]
[0001-Fix-ApiScopes-ApiResourceScopes.txt](https://github.com/RockSolidKnowledge/IdentityServer4.Migration.Scripts/files/7364837/0001-Fix-ApiScopes-ApiResourceScopes.txt)

**Comment by rehcra22** [comment]
Hi there - I can see you've adjusted the query to bring across the `Id` field from the `ApiScopes` table. Would you mind explaining what your use case for this change is as these fields are not tied to any foreign key relationships in the IdentityServer schema.

**Comment by djek-sweng** [comment]
When running your script I got this error.

[ERROR in query 21] Field 'Id' doesn't have a default value
Execution stopped!

This error is thrown by the insert into command at ApiScopes -> ApiResourceScopes.

You could also create the table with like this:

CREATE TABLE `ApiResourceScopes` (
    `Id` int NOT NULL auto_increment,

When using the auto_increment method, you can leave the insert statement as it is.

[0001-MySQL-query-auto_increment-primary-keys.txt](https://github.com/RockSolidKnowledge/IdentityServer4.Migration.Scripts/files/7365865/0001-MySQL-query-auto_increment-primary-keys.txt)

I like your work and will use it as a starting point for my IdentityServer migration.

**Comment by rehcra22** [comment]
Hi there - thanks for bringing this to our attention, would you be willing to create a PR and we'll get that merged in as soon as we can? Thanks for your vote of confidence in our work too! :)

**Comment by djek-sweng** [comment]
Hi Ben, I created a PR for this issue.

**Comment by rehcra22** [comment]
Thank you for your time!
